-- Create core tables for the stock pipeline

CREATE OR REPLACE TABLE RAW_STOCK_PRICES (
    SYMBOL         STRING,
    TRADE_DATE     DATE,
    OPEN_PRICE     FLOAT,
    HIGH_PRICE     FLOAT,
    LOW_PRICE      FLOAT,
    CLOSE_PRICE    FLOAT,
    VOLUME         NUMBER,
    LOAD_TS        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CLEAN_STOCK_PRICES AS
SELECT
    UPPER(SYMBOL)      AS SYMBOL,
    TRADE_DATE,
    OPEN_PRICE,
    HIGH_PRICE,
    LOW_PRICE,
    CLOSE_PRICE,
    VOLUME,
    LOAD_TS
FROM RAW_STOCK_PRICES
WHERE TRADE_DATE IS NOT NULL;

CREATE OR REPLACE TABLE STOCK_DAILY_METRICS AS
SELECT
    SYMBOL,
    TRADE_DATE,
    CLOSE_PRICE,
    LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE) AS PREV_CLOSE,
    CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE) AS PRICE_CHANGE,
    (CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE))
        / NULLIF(LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE), 0) AS PCT_CHANGE,
    VOLUME
FROM CLEAN_STOCK_PRICES;
