-- Create a task to refresh clean and analytics layers on a schedule

CREATE OR REPLACE TASK TASK_REFRESH_STOCK_LAYERS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 2 * * * America/New_York'
AS
BEGIN
    CREATE OR REPLACE TABLE CLEAN_STOCK_PRICES AS
    SELECT
        UPPER(SYMBOL) AS SYMBOL,
        TRADE_DATE,
        OPEN_PRICE,
        HIGH_PRICE,
        LOW_PRICE,
        CLOSE_PRICE,
        VOLUME,
        LOAD_TS
    FROM RAW_STOCK_PRICES
    WHERE TRADE_DATE IS NOT NULL;

    CREATE OR REPLACE TABLE STOCK_DAILY_METRICS AS
    SELECT
        SYMBOL,
        TRADE_DATE,
        CLOSE_PRICE,
        LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE) AS PREV_CLOSE,
        CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE) AS PRICE_CHANGE,
        (CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE))
            / NULLIF(LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE), 0) AS PCT_CHANGE,
        VOLUME
    FROM CLEAN_STOCK_PRICES;
END;
